Add email actions to Environments endpoint.
typhonius/acquia-php-sdk-v2 pull request #314
Opened 2023-01-26 23:01 UTC by fiasco

This change allows support for enable/disable actions for Platform Email on the Environments endpoint.

2023-01-27 15:35 UTC, danepowell requested changes
The tests on this project are super easy to run locally: `composer test`

2023-01-27 15:35 UTC, danepowell commented on tests/Endpoints/EnvironmentsTest.php
> +    public testEnableEmail(): void
```suggestion
    public function testEnableEmail(): void
```

2023-01-27 15:35 UTC, danepowell commented on tests/Endpoints/EnvironmentsTest.php
> +    public testDisableEmail(): void
```suggestion
    public function testDisableEmail(): void
```

2023-01-28 21:01 UTC, danepowell approved these changes

2023-01-28 21:02 UTC, danepowell requested changes
Looks like you've still got failing tests. Let me know if you're having problems running them locally.

2023-02-03 06:45 UTC, fiasco commented
I tried out github's IDE but it doesn't provide an executable environment...

2023-02-03 18:07 UTC, danepowell commented
> I tried out github's IDE but it doesn't provide an executable environment...

That doesn't sound right. I just created a codespace, immediately saw a terminal window and typed `composer install && composer test`, everything worked great. Well, except for the failing tests :)

2023-02-07 18:38 UTC, danepowell commented
Sorry, looks like you got bit by #317. I updated your PR so tests will at least run and pass, but we'll need for #317 to be merged first.

2023-02-07 18:46 UTC, danepowell commented
I have no clue why mutation tests are failing now. Some wires have really gotten crossed somewhere because they claim composer.lock still has a reference to phpunit 9.6.3, which it certainly does not. Possibly because you are using `master` instead of a feature branch? 😕

2023-02-08 19:47 UTC, danepowell commented
Sorry, now blocked on https://github.com/codecov/codecov-action/issues/837

2023-02-08 20:14 UTC, merged